steps:
- name: 'gcr.io/cloud-builders/mvn'
args: ['test']
- name: 'gcr.io/cloud-builders/mvn'
args: ['package']
- name: 'gcr.io/cloud-builders/docker'
args: ['build', '-t', 'gcr.io/$PROJECT_ID/itacorubi', '.'] - name: 'gcr.io/cloud-builders/docker'
args: ['push', 'gcr.io/$PROJECT_ID/itacorubi'] - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
entrypoint: gcloud args: [
        "beta", "deploy", "releases", "create", "rel-\${SHORT_SHA}",
        "--delivery-pipeline", "itacorubi-pipeline",
        "--region", "us-central1",
        "--annotations", "commitId=\${REVISION_ID}",
        "--images", "itacorubi=gcr.io/$PROJECT_ID/itacorubi"
        ]

