steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['-C', 'data-collection', 'submodule', 'sync', '--recursive']
- name: 'gcr.io/cloud-builders/git'
  args: ['-C', 'data-collection', 'submodule', 'update', '--init', '--recursive']
- name: 'gcr.io/cloud-builders/mvn'
  args: ['package']
  dir: 'data-collection'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-image:${TAG_NAME}', '.']
  dir: 'data-collection'
images:
- 'gcr.io/$PROJECT_ID/my-image:${TAG_NAME}'
